apiVersion: v1alpha1
kind: ComponentConfig
metadata:
  name: cartservice
  projectName: gcp-demo
  annotations:
    componentType: service
spec:
  inbound:
  - name: cartservice
    port: 9090
    type: REST
    visibility: Public
    context: /
  outbound:
    serviceReferences:
    - name: choreo:///asmaj/lpar/auvzlk/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/redis/public
      dependentConfig: config-1
      connectionType: datastore
